--MOVIES
--INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '케데헌 URL', '케이팝 데몬 헌터스', '12', TO_DATE('2025.10.31', 'YYYY.MM.DD'), 'KR', 96, 'They sing. They dance. They battle demons.', '케이팝 슈퍼스타 루미, 미라, 조이. 매진을 기록하는 대형 스타디움 공연이 없을 때면 이들은 또 다른 활동에 나선다. 바로 비밀 능력을 이용해 팬들을 초자연적 위협으로부터 보호하는 것.', 'KPOP Demon Hunters ', '개봉됨', '영어', 100000000, 24690793);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '헬프 포스터 URL', '헬프 ! ', 'U', TO_DATE('1965.07.29', 'YYYY.MM.DD'), 'GB', 92, 'Stop worrying! HELP! is on the way!', '우연히 암흑의 여왕에 바쳐지는 제물이 된 링고를 구하기 위해 비틀즈 멤버들이 고군분투한다.', 'HELP!', '개봉됨', '영어', 1500000, NULL);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '케데헌2 URL', 'Untitled Kpop Demon Hunters Sequel', '', TO_DATE('', 'YYYY.MM.DD'), '', NULL, '', 'The second installment in the franchise. Plot TBA.', '', '제작 예정', '영어', NULL, NULL);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '첸쏘맨 URL', '극장판 체인소 맨 : 레제편', '15', TO_DATE('2025.09.24', 'YYYY.MM.DD'), 'KR', 100, '아무도 모르는, 소녀의 마음 ', '데블 헌터로 일하는 소년 ‘덴지’는 조직의 배신으로 죽음에 내몰린 순간 전기톱 악마견 ‘포치타’와의 계약으로 하나로 합쳐져 누구도 막을 수 없는 존재 ‘체인소 맨’으로 다시 태어난다. 악마와 사냥꾼, 그리고 정체불명의 적들이 얽힌 잔혹한 전쟁 속에서 ‘레제’라는 이름의 미스터리한 소녀가 ‘덴지’ 앞에 나타나는데… ‘덴지’는 사랑이라는 감정에 이끌려 지금껏 가장 위험한 배틀에 몸을 던진다!', '劇場版 チェンソーマン レゼ篇', '개봉됨', '일본어', 4100000, 174502910);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '토마토 URL', '토마토 공격대', 'PG', TO_DATE('1978.10.04', 'YYYY.MM.DD'), 'US', 87, 'A new musical-comedy-horror show!', '식탁에 있던 토마토들이 어느 날 갑자기 사람들을 공격하기 시작하면서 토마토와 인간은 한바탕 전쟁을 벌이기 시작한다!', 'Attack of the Killer Tomatoes!', '개봉됨', '영어', 100420, 567000);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '바스터즈 URL', '바스터즈: 거친 녀석들', '18', TO_DATE('2009.10.28', 'YYYY.MM.DD'), 'KR', 152, '가장 쿨한 녀석들의 통쾌한 복수', '2차 세계 대전, 나치의 잔인하고 폭력적인 행태에 분개한 미군 알도 레인 중위는 당한 만큼 돌려준다는 강렬한 신념으로 최고의 재능을 가진 8명의 대원을 모아 바스터즈란 군단을 만들어 나치가 점령한 프랑스에 잠입해 복수를 시작한다. 어느 날 알도 레인 중위는 독일의 여배우이자 영국의 더블 스파이인 브리짓에게 뜻밖의 소식을 듣는다. 나치 수뇌부가 모두 참석하는 독일 전쟁 영화의 프리미어에 히틀러도 참석을 한다는 것. 한 번에 나치를 모두 쓸어버릴 계획으로 바스터즈는 이탈리아 영화 관계자로 분장해 극장으로 향하는데...', 'Inglourious Basterds', '개봉됨', '영어', 70000000, 321457747);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '익스트렉션 URL', '익스트랙션', '19', TO_DATE('2020.04.24', 'YYYY.MM.DD'), 'KR', 116, ' When the mission ends, redemption begins', '어떤 일에도 쉽게 동요하지 않는 냉철한 청부업자. 그가 살아남기 위해 자신을 끊임없이 성찰한다. 마약왕의 납치된 아들을 구하러 간 방글라데시에서 그 모든 것이 시작됐다.', 'Extraction', '개봉됨', '영어', 65000000, NULL);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '1917 URL', '1917', '15', TO_DATE('2020.02.19', 'YYYY.MM.DD'), 'KR', 119, '그들이 싸워야 할 것은 적이 아니라 시간이었다', '제1차 세계대전이 한창인 1917년 4월 6일. 독일군에 의해 모든 통신망이 파괴된 상황 속에서 서부전선의 영국군 병사 스코필드와 블레이크에게 하나의 미션이 주어졌다. 독일군의 함정에 빠진 영국군 부대의 수장 매켄지 중령에게 에린무어 장군의 공격 중지 명령을 전달하라는 것. 블레이크는 데본셔 연대에 있는 형을 구하기 위해 기꺼이 임무를 수행한다. 동료인 스코필드는 처음엔 당황스러워하지만 이내 1600명의 동료들을 구하기 위해 전쟁터 한가운데를 가로지르는 여정에 동참한다.', '', '개봉됨', '영어', 100000000, 446064352);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '인셉션 URL ', '인셉션', '12', TO_DATE('2010.07.21', 'YYYY.MM.DD'), 'KR', 148, '생각을 훔치는 거대한 전쟁', '타인의 꿈에 들어가 생각을 훔치는 특수 보안요원 코브. 그를 이용해 라이벌 기업의 정보를 빼내고자 하는 사이토는 코브에게 생각을 훔치는 것이 아닌, 생각을 심는 ‘인셉션’ 작전을 제안한다. 성공 조건으로 국제적인 수배자가 되어있는 코브의 신분을 바꿔주겠다는 거부할 수 없는 제안을 하고, 사랑하는 아이들에게 돌아가기 위해 그 제안을 받아들인다. 최강의 팀을 구성, 표적인 피셔에게 접근해서 ‘인셉션’ 작전을 실행하지만 예기치 못한 사건들과 마주하게 되는데… 꿈 VS 현실! 시간, 규칙, 타이밍 모든 것이 완벽해야만 하는, 단 한 번도 성공한 적 없는 ‘인셉션’ 작전이 시작된다!', 'Inception', '개봉됨', '영어', 160000000, 839030630);
INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, "LANGUAGE", BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '존 윅 URL', '존 윅', '19', TO_DATE('2015.01.21', 'YYYY.MM.DD'), 'KR', 101, '그를 건드리지 말았어야 했다', '전설이라 불리던 킬러 존 윅은 사랑하는 여인을 만나 결혼을 하면서 범죄의 세계에서 은퇴한다. 행복도 잠시, 투병 끝에 부인이 세상을 떠나고 그의 앞으로 부인이 죽기 전에 보낸 강아지 한 마리가 선물로 배달된다. 어느 날 그의 차를 탐낸 러시아 마피아의 일원 요세프가 존 윅을 폭행하고 애완견 데이지마저 죽여버리는 일이 벌어진다. 그런데 요세프는 과거 존 윅을 고용한 적 있는 러시아 마피아 보스 비고의 아들이다. 마지막 남은 애완견마저 잃은 존 윅은 이제 그만의 방식으로 복수를 시작하는데...', 'John Wick', '개봉됨', '영어', 20000000, 88761661);
--INSERT INTO MOVIES (MOVIE_ID, POSTER_URL, TITLE, MOVIE_RATING, OPEN_DATE, OPEN_COUNTRY, RUNNING_TIME, INTRODUCE, SYNOPSIS, ORIGNAL_TITLE, STATE, LANGUAGE, BUDGET, PROFIT) VALUES ('MV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MOVIES_PK.NEXTVAL, 6, 0), '
--=TEXTJOIN("', '",FALSE,B2:L2, IF(M2<>"",M2, NULL),IF(N2<>"",N2, NULL)) & "');"

-- ACTORS
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '아덴 조','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '메이 홍 ','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '유지영','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '안효섭','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '김윤진','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '켄 정','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '이병헌 ','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '다니엘 대 킴','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '조엘 김 부스터','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '조지 해리슨','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '존 레논','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '폴 매카트니','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '링고 스타','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Leo McKern','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Eleanor Bron ','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Victor Spinetti','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Roy Kinnear','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'John Bluthal','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '토야 키쿠노스케 ','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '우에다 레이나','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '쿠스노키 토모리','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '사카타 쇼고','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '우치다 마아야','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '하나에 나츠키','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '타카하시 카린','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '파이루즈 아이','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '우치다 유우야','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'David Miller','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'George Wilson','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Sharon Taylor','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'J. Stephen Peace','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Ernie Meyers','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Eric Christmas','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Jack Riley','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Nigel Barber','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'John De Bello','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '브래드 피트','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '멜라니 로랑','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '크리스토프 발츠','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '일라이 로스','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '마이클 패스벤더','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '다이앤 크루거','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '다니엘 브륄','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '틸 슈바이거','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Gedeon Burkhard','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '크리스 햄스워스','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Rudhraksh Jaiswal','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Randeep hooda','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '골쉬프테 파라하니','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Pankaj Tripathi','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '데이비드 하버','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Bryon Lerum','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Ryder Lerum','');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Shivam Vichare','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '조지 맥케이 ','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '딘-찰스 채프먼','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '마크 스트롱','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '앤드류 스콧','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '리차드 매든','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '클레어 듀버크','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '콜린 퍼스','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '베네딕트 컴버배치','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '다니엘 메이스','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '레오나르도 디카프리오','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '조셉 고든레빗','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '와타나베 켄','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '톰 하디','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '엘리엇 페이지','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '딜립 라오 ','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '킬리언 머피','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '톰 베렌저','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '마리옹 꼬띠아르','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '키아누 리브스','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '미카엘 니크비스트','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '알피 앨런','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '월렘 대포','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '딘 윈터스','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '에이드리언 팰리키','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Omer Barnea','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), 'Toby Leonard Moore','배우사진');
INSERT INTO ACTORS (ACTOR_ID, ACTOR_NAME, PROFILE_PIC) VALUES ('AC-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_ACTORS_PK.NEXTVAL, 6, 0), '다니엘 베른하르트','배우사진');

--FILMOGRAPHY
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000001', 'Rumi (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000002', 'Mira (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000003', 'Zoey (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000004', 'Jinu (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000005', 'Celine (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000006', 'Bobby (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000007', 'Gwi-Ma (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000008', 'Healer Han (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000008', 'Additional Voices (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000008', 'Variety Show Host 1 (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000009', 'Idol Host (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'AC-20260227-000009', 'Romance Saja (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000010', 'George');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000011', 'John');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000012', 'Paul');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000013', 'Ringo');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000014', 'Clang');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000015', 'Ahme');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000016', 'Prof.Foot');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000017', 'Algernon');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'AC-20260227-000018', 'Bhuta');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000019', 'Denji (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000020', 'Reze (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000021', 'Makima (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000022', 'Aki (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000023', 'Angel Devil (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000024', 'Beam (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000025', 'Kobeni (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000026', 'Power (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000004', 'AC-20260227-000027', 'The Violence Fiend (voice)');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000028', 'Mason Dixon');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000029', 'Jim Richardson');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000030', 'Lois Fairchild');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000031', 'Wilbur Finletter');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000032', 'The President');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000033', 'Senator Polk');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000034', 'Salesman');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000035', 'Guard at Gate');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000036', 'Janitor');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000005', 'AC-20260227-000036', 'Charles White');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000037', 'LT.Aldo Raine');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000038', 'Shosanna');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000039', 'COL. Hans Landa');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000040', 'SGT.Donny Donowitz');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000041', 'LT.Archie Hicox');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000042', 'Bridget von Hammersmark');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000043', 'Fredrick Zoller');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000044', 'SGT. Hugo Stiglitz');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000006', 'AC-20260227-000045', 'CPL. Wilhelm Wicki');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000046', 'Tyler Rake');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000047', 'Ovi Mahajan');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000048', 'Saju');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000049', 'Nik Khan');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000050', 'Ovi Mahajan Sr.');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000051', 'Gaspar');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000052', 'Rake''s Son');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000053', 'Rake''s Son');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000007', 'AC-20260227-000054', 'Sachin');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000055', 'Lance Corporal Schofield');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000056', 'Lance Corporal Blake');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000057', 'Captain Smith');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000058', 'Lieutanant Leslie');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000059', 'Lieutanant Blake');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000060', 'Lauri');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000061', 'General Erinmore');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000062', 'Colonel Mackenzie');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000008', 'AC-20260227-000063', 'Sergeant Sanders');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000064', 'Dom Cobb');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000065', 'Arthur');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000066', 'Saito');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000067', 'Eames');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000068', 'Ariadne');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000069', 'Yusuf');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000070', 'Robert Fischer, Jr.');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000071', 'Peter Browing');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000009', 'AC-20260227-000072', 'Mal Cobb');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000073', 'John Wick');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000074', 'Viggo Tarasov');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000075', 'Iosef Tarasov');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000076', 'Marcus');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000077', 'Avi');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000078', 'Ms. Perkins');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000079', 'Gregori');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000080', 'Victor');
INSERT INTO FILMOGRAPHY (FILMOGRAPHY_ID, MOVIE_ID, ACTOR_ID, ACTOR_ROLE) VALUES ('FL-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_FILMOGRAPHY_PK.NEXTVAL, 6, 0), 'MV-20260227-000010', 'AC-20260227-000081', 'Kirill');

--PRODUCERS
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '매기 강');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '크리스아펠한스');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '다나 히메네스');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '해나 맥메찬');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Marc Behm');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Richard Lester');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Charles Wood');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '요시하라 타츠야');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '세코 히로시');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'John De Bello');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Costa Dillon');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Rick Rockwell');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'J. Stephen Peace');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '샘 멘데스');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Krysty Wilson-Cairns');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '크리스토퍼 놀란');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '채드 스타헬스키');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), 'Derek Kolstad');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '쿠엔틴 타란티노');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '샘 하그레이브');
INSERT INTO PRODUCERS (PRODUCER_ID, PRODUCER_NAME) VALUES ('PD-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_PRODUCERS_PK.NEXTVAL, 6, 0), '조 루소');

--MAKE
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000001', 'MV-20260227-000001', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000001', 'MV-20260227-000001', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000001', 'MV-20260227-000001', 'Story', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000001', 'MV-20260227-000003', 'Director', '');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000001', 'MV-20260227-000003', 'Writer', '');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000002', 'MV-20260227-000001', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000002', 'MV-20260227-000001', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000002', 'MV-20260227-000003', 'Director', '');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000002', 'MV-20260227-000003', 'Writer', '');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000003', 'MV-20260227-000001', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000004', 'MV-20260227-000001', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000005', 'MV-20260227-000002', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000005', 'MV-20260227-000002', 'Story', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000006', 'MV-20260227-000002', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000007', 'MV-20260227-000002', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000008', 'MV-20260227-000004', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000009', 'MV-20260227-000004', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000010', 'MV-20260227-000005', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000010', 'MV-20260227-000005', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000011', 'MV-20260227-000005', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000012', 'MV-20260227-000005', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000013', 'MV-20260227-000005', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000019', 'MV-20260227-000006', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000019', 'MV-20260227-000006', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000020', 'MV-20260227-000007', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000021', 'MV-20260227-000007', 'Screenplay', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000014', 'MV-20260227-000008', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000014', 'MV-20260227-000008', 'Writer', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000015', 'MV-20260227-000008', 'Writer', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000016', 'MV-20260227-000009', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000016', 'MV-20260227-000009', 'Writer', '각본');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000017', 'MV-20260227-000010', 'Director', '연출');
INSERT INTO MAKE (MAKE_ID, PRODUCER_ID, MOVIE_ID, PRODUCER_ROLE, PRODUCER_PART) VALUES ('MK-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_MAKE_PK.NEXTVAL, 6, 0), 'PD-20260227-000018', 'MV-20260227-000010', 'Writer', '각본');

--CATEGORIES
INSERT INTO CATEGORIES (CATEGORIE_ID, CATEGORIE_NAME) VALUES ('CT-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_CATEGORIES_PK.NEXTVAL, 6, 0), '판타지');
INSERT INTO CATEGORIES (CATEGORIE_ID, CATEGORIE_NAME) VALUES ('CT-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_CATEGORIES_PK.NEXTVAL, 6, 0), '음악');
INSERT INTO CATEGORIES (CATEGORIE_ID, CATEGORIE_NAME) VALUES ('CT-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_CATEGORIES_PK.NEXTVAL, 6, 0), '코미디');
INSERT INTO CATEGORIES (CATEGORIE_ID, CATEGORIE_NAME) VALUES ('CT-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_CATEGORIES_PK.NEXTVAL, 6, 0), '애니메이션');
INSERT INTO CATEGORIES (CATEGORIE_ID, CATEGORIE_NAME) VALUES ('CT-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_CATEGORIES_PK.NEXTVAL, 6, 0), '모험');
INSERT INTO CATEGORIES (CATEGORIE_ID, CATEGORIE_NAME) VALUES ('CT-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_CATEGORIES_PK.NEXTVAL, 6, 0), '가족');


--GENRE
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'CT-20260227-000001');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'CT-20260227-000002');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'CT-20260227-000003');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000001', 'CT-20260227-000004');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'CT-20260227-000002');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'CT-20260227-000003');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000002', 'CT-20260227-000005');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000003', 'CT-20260227-000006');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000003', 'CT-20260227-000001');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000003', 'CT-20260227-000002');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000003', 'CT-20260227-000005');
INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), 'MV-20260227-000003', 'CT-20260227-000004');

--="INSERT INTO GENRE (GENRE_ID, MOVIE_ID, CATEGORIE_ID) VALUES ('GN-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_GENRE_PK.NEXTVAL, 6, 0), '" & TEXTJOIN("', '",FALSE,) & "');"









