--1. 모든 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID 
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
;
--2. 부서가 없는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.DEPARTMENT_ID IS NULL
;
--3. 직무가 없는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.JOB_ID IS NULL
;
--4. 부서와 직무가 모두 있는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.DEPARTMENT_ID IS NOT NULL
   AND E.JOB_ID IS NOT NULL
;
--5. 부서장이 없는 모든 부서의 모든 정보를 조회한다.
SELECT D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME
	 , D.MANAGER_ID
	 , D.LOCATION_ID
  FROM DEPARTMENTS D
 WHERE D.MANAGER_ID IS NULL
;
--6. 부서장이 있는 모든 부서의 모든 정보를 조회한다.
SELECT D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME
	 , D.MANAGER_ID
	 , D.LOCATION_ID
  FROM DEPARTMENTS D
 WHERE D.MANAGER_ID IS NOT NULL
;
--7. 사원의 이름만 조회한다.
SELECT CONCAT(E.FIRST_NAME, E.LAST_NAME) AS NAME
  FROM EMPLOYEES E
;
--8. 모든 지역의 모든 정보를 조회한다.
SELECT L.LOCATION_ID
	 , L.STREET_ADDRESS
	 , L.POSTAL_CODE
	 , L.CITY
	 , L.STATE_PROVINCE
	 , L.COUNTRY_ID
  FROM LOCATIONS L
;
--9. 지역이 없는 모든 부서의 정보를 조회한다.
SELECT D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME
	 , D.MANAGER_ID
	 , D.LOCATION_ID
  FROM DEPARTMENTS D
-- LEFT OUTER JOIN LOCATIONS L
--    ON D.LOCATION_ID = L.LOCATION_ID
 WHERE D.LOCATION_ID IS NULL
;