CREATE TABLE "MOVIES" (
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"POSTER_URL"	VARCHAR2(2048 CHAR)		NOT NULL,
	"TITLE"	VARCHAR2(50 CHAR)		NOT NULL,
	"MOVIE_RATING"	VARCHAR2(3 CHAR)		NULL,
	"OPEN_DATE"	DATE		NULL,
	"OPEN_COUNTRY"	VARCHAR2(2 CHAR)		NULL,
	"RUNNING_TIME"	NUMBER(4, 0)		NULL,
	"INTRODUCE"	VARCHAR2(60 CHAR)		NULL,
	"SYNOPSIS"	VARCHAR2(4000 CHAR)		NOT NULL,
	"ORIGNAL_TITLE"	VARCHAR2(50 CHAR)		NULL,
	"STATE"	VARCHAR2(5 CHAR)		NOT NULL,
	"LANGUAGE"	VARCHAR2(6 CHAR)		NOT NULL,
	"BUDGET"	NUMBER(11, 2)		NULL,
	"PROFIT"	NUMBER(12, 2)		NULL
);

COMMENT ON COLUMN "MOVIES"."MOVIE_ID" IS 'MV-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "PRODUCERS" (
	"PRODUCER_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"PRODUCER_NAME"	VARCHAR2(40 CHAR)		NULL
);

COMMENT ON COLUMN "PRODUCERS"."PRODUCER_ID" IS 'PD-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "CATEGORIES" (
	"CATEGORIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"CATEGORIE_NAME"	VARCHAR2(40 CHAR)		NOT NULL
);

COMMENT ON COLUMN "CATEGORIES"."CATEGORIE_ID" IS 'CT-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "GENRE" (
	"GENRE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"CATEGORIE_ID"	VARCHAR2(18 CHAR)		NOT NULL
);

COMMENT ON COLUMN "GENRE"."GENRE_ID" IS 'GE-YYYYMMDD-SEQUENCE(6)';

COMMENT ON COLUMN "GENRE"."MOVIE_ID" IS 'MV-YYYYMMDD-SEQUENCE(6)';

COMMENT ON COLUMN "GENRE"."CATEGORIE_ID" IS 'CT-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "ACTORS" (
	"ACTOR_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"ACTOR_NAME"	VARCHAR2(40 CHAR)		NOT NULL,
	"PROFILE_PIC"	VARCHAR2(2048 CHAR)		NULL
);

COMMENT ON COLUMN "ACTORS"."ACTOR_ID" IS 'AC-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "MAKE" (
	"MAKE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"PRODUCER_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"PRODUCER_ROLE"	VARCHAR2(40 CHAR)		NOT NULL,
	"PRODUCER_PART"	VARCHAR2(40 CHAR)		NULL
);

COMMENT ON COLUMN "MAKE"."MAKE_ID" IS 'MK-YYYYMMDD-SEQUENCE(6)';

COMMENT ON COLUMN "MAKE"."MOVIE_ID" IS 'MV-YYYYMMDD-SEQUENCE(6)';

COMMENT ON COLUMN "MAKE"."PRODUCER_ID" IS 'PD-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "FILMOGRAPHY" (
	"FILMOGRAPHY_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"MOVIE_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"ACTOR_ID"	VARCHAR2(18 CHAR)		NOT NULL,
	"ACTOR_ROLE"	VARCHAR2(40 CHAR)		NOT NULL
);

COMMENT ON COLUMN "FILMOGRAPHY"."FILMOGRAPHY_ID" IS 'FL-YYYYMMDD-SEQUENCE(6)';

COMMENT ON COLUMN "FILMOGRAPHY"."MOVIE_ID" IS 'MV-YYYYMMDD-SEQUENCE(6)';

COMMENT ON COLUMN "FILMOGRAPHY"."ACTOR_ID" IS 'AC-YYYYMMDD-SEQUENCE(6)';

ALTER TABLE "MOVIES" ADD CONSTRAINT "PK_MOVIES" PRIMARY KEY (
	"MOVIE_ID"
);

ALTER TABLE "PRODUCERS" ADD CONSTRAINT "PK_PRODUCERS" PRIMARY KEY (
	"PRODUCER_ID"
);

ALTER TABLE "CATEGORIES" ADD CONSTRAINT "PK_CATEGORIES" PRIMARY KEY (
	"CATEGORIE_ID"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE_ID"
);

ALTER TABLE "ACTORS" ADD CONSTRAINT "PK_ACTORS" PRIMARY KEY (
	"ACTOR_ID"
);

ALTER TABLE "MAKE" ADD CONSTRAINT "PK_MAKE" PRIMARY KEY (
	"MAKE_ID"
);

ALTER TABLE "FILMOGRAPHY" ADD CONSTRAINT "PK_FILMOGRAPHY" PRIMARY KEY (
	"FILMOGRAPHY_ID"
);

